package com.wordrpess.marianbuenosayres;

import com.wordpress.marianbuenosayres.model.Requirement;

rule "prioritize requirements with lots of bugs"
lock-on-active
when
    r: Requirement(bugs.size() > 3)
then
    r.setPriority(20 / r.getBugs().size());
    update(r);
end

rule "prioritize requirements with URGENT on the name"
lock-on-active
when
    r: Requirement(name matches ".*(urgent|URGENT).*")
then
    r.setPriority(1);
    update(r);
end

rule "default priority for other cases"
salience -1
when
    r: Requirement(priority == -1)
then
    r.setPriority(10);
end

